# must accept EULA the first time that the image is started
# docker run splunk/enterprise:7.0.3
# Options on how to review the EULA and accept it: 
# 1. docker run -it splunk/enterprisetrial:7.0.3
# 2. Add the following environment variable: SPLUNK_START_ARGS=--accept-license
# e.g., docker run -e "SPLUNK_START_ARGS=--accept-license" splunk/enterprisetrial 

# Support for Docker Compose v3, https://docs.docker.com/compose/overview/
version: '3.6'

services:
  splunkestandalone:
    image: splunk/splunk:7.2.0
    build:
      context: ./
      dockerfile: ./Dockerfile
    hostname: splunkstandalone
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_ROLE: splunk_standalone
      SPLUNK_ENABLE_LISTEN: 9997
      SPLUNK_ADD: tcp 1514
      DEBUG: "true"
    volumes:
      - type: volume
        source: opt-splunk-etc
        target: /opt/splunk/etc/
      - type: volume
        source: opt-splunk-var
        target: /opt/splunk/var/
      - type: bind
        source: ./ansible-configs/defaults
        target: /tmp/defaults
    ports:
      - "8000:8000"
      - "9997:9997"
      - "8088:8088"
      - "1514:1514"

volumes:
  opt-splunk-etc:
  opt-splunk-var:
